set:
  # 是否开启调试模式，消息只会在终端输出，不会推送到微信
  debug: False
  # 发送人的昵称
  send_name: 'XX'
  # 接收人的昵称
  receive_name: 'XX'

city:
  # 城市名称，暂时无用
  name: '上海'
  # 城市代号 其他城市请参考 city.json 文件
  code: '101020100'

pushbear:
  # 接口地址
  api: 'https://pushbear.ftqq.com/sub'
  # 消息标题
  title: '提醒事项'
  # 申请地址 https://pushbear.ftqq.com
  key: ''

tips:
  - {time: '6:30', msg: '经过一整夜的睡眠，身体开始缺水，起床之际先喝杯250ml的水，【先刷牙，再喝水。水要温水】可帮助肾脏及肝脏解毒,还可帮助清洁胃肠道。别马上吃早餐，等待半小时让水融入每个细胞，进行新陈代谢后，再进食！（非常重要！身体排污靠它！）'}
  - {time: '8:30', msg: '清晨从起床到办公室的过程，时间总是特别紧凑，情绪也较紧张，身体无形中会出现脱水现象，所以到了办公室后，先别急着泡咖啡，给自己一杯至少250ml的水！'}
  - {time: '11:0', msg: '在空调房里工作一段时间后，一定得趁起身动动的时候，再给自己一天里的第三杯水，补充流失的水分，有助于放松紧张的工作情绪。'}
  - {time: '12:50', msg: '用完午餐半小时后，喝一些水，取代让你发胖的人工饮料，可以加强身体的消化功能，不仅对健康有益，也能助你维持身材。'}
  - {time: '15:0', msg: '以一杯健康矿泉水代替午茶与咖啡等提神饮料吧！喝上一大杯水，除了补充在冷气房里流失的水份之外，还能帮助头脑清醒。'}
  - {time: '17:30', msg: '下班离开办公室前，再喝一杯水。想要运用喝水减重的，可以多喝几杯，增加饱足感，待会吃晚餐时，自然不会暴饮暴食。'}
  - {time: '22:0', msg: '睡前一至半小时再喝上一杯水，不过别一口气喝太多，以免晚上得上洗手间影响睡眠品质。今天已摄取2000ml水量了。目标达成！'}
